# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Don't trigger on commits
trigger: none

# Run o schedule
pr:
  drafts: false
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - .github/*
    - README.md

jobs:
- job: PR_Build
  pool:
    name: Intranet Server

  steps:
  - powershell: git clone https://github.com/intervip/core.git ../core
    displayName: 'Download Intervip Core library'
  - task: UseDotNet@2
    displayName: 'Download .NET 7.x SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
      performMultiLevelLookup: true
      workingDirectory: '$(Build.SourcesDirectory)'
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'
      feedsToUse: config
      nugetConfigPath: './nuget.config'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.Tests.csproj'
      arguments: '--no-restore -c release'
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--no-build -c release --collect "Code coverage"'
  - powershell: rm -r -fo -v ..\core
    displayName: 'Cleanup Core Library directory'